In [2]:
import numpy as np
mat1_53=np.array([[5,3,2],[6,3,8]])
mat2_53=np.array([[6,8,3],[5,7,1]])
print("array1 :")
print(mat1_53)
print("array2 :")
print(mat2_53)
print("result")
print(np.multiply(mat1_53,mat2_53))

array1 :
[[5 3 2]
 [6 3 8]]
array2 :
[[6 8 3]
 [5 7 1]]
result
[[30 24  6]
 [30 21  8]]
