In [2]:
import numpy as np
arr53 = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(arr53)
print("\nswapping first and last rows of the said array:")
arr53[[0,-1],:]=arr53[[-1,0],:]
print(arr53)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]
