In [1]:
#1

import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    return array_1


arr1 = create_matrix(1)
arr2 = create_matrix(2)

if(arr1.shape == arr2.shape):
    print("\nDot product")
    print(np.dot(arr1,arr2))
else:
    print("\nDimensions not matching!")



ARRAY 1 Elements : 


 1 2 3



ARRAY 1 ,  ROW COLUMN : 


 2 3



Row and Column size not match with total elements !! retry

ARRAY 1 Elements : 


 3 4 5 5



ARRAY 1 ,  ROW COLUMN : 


 2 2



ARRAY 1
[[3 4]
 [5 5]]

ARRAY 2 Elements : 


 4 5 6 7



ARRAY 2 ,  ROW COLUMN : 


 2 2



ARRAY 2
[[4 5]
 [6 7]]

Dot product
[[36 43]
 [50 60]]


In [2]:
#2

import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    print("\nTranspose : ")
    return array_1



print(create_matrix(1).transpose())


ARRAY 1 Elements : 


 2 3 5 6 7 8  9  8



ARRAY 1 ,  ROW COLUMN : 


 2 4 



ARRAY 1
[[2 3 5 6]
 [7 8 9 8]]

Transpose : 
[[2 7]
 [3 8]
 [5 9]
 [6 8]]


In [3]:
#3

import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    print("\nTrase : ")
    return array_1



print(create_matrix(1).trace())


ARRAY 1 Elements : 


 4 5 6 7 8 7



ARRAY 1 ,  ROW COLUMN : 


 2 3



ARRAY 1
[[4 5 6]
 [7 8 7]]

Trase : 
12


In [4]:
#4

import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    print("\nRank : ")
    return array_1



print(np.linalg.matrix_rank(create_matrix(1)))



ARRAY 1 Elements : 


 4 6 3 8



ARRAY 1 ,  ROW COLUMN : 


 2 2 



ARRAY 1
[[4 6]
 [3 8]]

Rank : 
2


In [5]:
#5

import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    print("\nDeterminant : ")
    return array_1



print(np.linalg.det(create_matrix(1)))



ARRAY 1 Elements : 


 3 5 6 1



ARRAY 1 ,  ROW COLUMN : 


 2 2 



ARRAY 1
[[3 5]
 [6 1]]

Determinant : 
-27.0


In [6]:
#6

import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    print("\nInverse : ")
    return array_1



print(np.linalg.inv(create_matrix(1)))



ARRAY 1 Elements : 


 4 5 6 1



ARRAY 1 ,  ROW COLUMN : 


 2 2



ARRAY 1
[[4 5]
 [6 1]]

Inverse : 
[[-0.03846154  0.19230769]
 [ 0.23076923 -0.15384615]]


In [7]:
#7

import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    return array_1



x,y = np.linalg.eig(create_matrix(1))

print("\nE-value : ")
print(x)
print("\nE-vector : ")
print(y)



ARRAY 1 Elements : 


 3 2 4 1



ARRAY 1 ,  ROW COLUMN : 


 2 2



ARRAY 1
[[3 2]
 [4 1]]

E-value : 
[ 5. -1.]

E-vector : 
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]
